"""initial schema - all 47 models

Revision ID: ecc1fda708e0
Revises: 
Create Date: 2026-04-03 03:35:37.782530
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ecc1fda708e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cfr_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('section', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chambers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('congresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_number')
    )
    op.create_table('congressional_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('volume', sa.String(length=20), nullable=True),
    sa.Column('issue', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=20), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('data_quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('check_name', sa.String(length=100), nullable=True),
    sa.Column('check_type', sa.String(length=50), nullable=True),
    sa.Column('records_checked', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_type', sa.String(length=50), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fec_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fec_candidate_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('office_sought', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('incumbent_active', sa.String(length=1), nullable=True),
    sa.Column('principal_committee_id', sa.String(length=20), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('election_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_candidate_id')
    )
    op.create_table('fec_committee_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fec_committee_id', sa.String(length=20), nullable=True),
    sa.Column('fec_candidate_id', sa.String(length=20), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fec_committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fec_committee_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('committee_type', sa.String(length=50), nullable=True),
    sa.Column('committee_designation', sa.String(length=50), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('treasurer_name', sa.String(length=200), nullable=True),
    sa.Column('street1', sa.String(length=100), nullable=True),
    sa.Column('street2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fec_committee_id')
    )
    op.create_table('federal_register',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('agency', sa.String(length=200), nullable=True),
    sa.Column('docket_number', sa.String(length=100), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('html_url', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_table('lobbying_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.String(length=50), nullable=True),
    sa.Column('registrant_name', sa.String(length=300), nullable=True),
    sa.Column('client_name', sa.String(length=300), nullable=True),
    sa.Column('lobby_year', sa.Integer(), nullable=True),
    sa.Column('income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expenses', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('filing_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('govtrack_id', sa.Integer(), nullable=True),
    sa.Column('thomas_id', sa.String(length=20), nullable=True),
    sa.Column('lis_id', sa.String(length=20), nullable=True),
    sa.Column('fec_id', sa.String(length=20), nullable=True),
    sa.Column('opensecrets_id', sa.String(length=20), nullable=True),
    sa.Column('vote_smart_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('contact_form_url', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('twitter_id', sa.String(length=100), nullable=True),
    sa.Column('youtube_id', sa.String(length=100), nullable=True),
    sa.Column('facebook_id', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('first_congress', sa.Integer(), nullable=True),
    sa.Column('last_congress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bioguide_id'),
    sa.UniqueConstraint('govtrack_id')
    )
    op.create_table('api_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('requests_made', sa.Integer(), nullable=True),
    sa.Column('limit_total', sa.Integer(), nullable=True),
    sa.Column('limit_reset', sa.DateTime(), nullable=True),
    sa.Column('last_request', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=False),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('display_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('popular_title', sa.Text(), nullable=True),
    sa.Column('short_title', sa.Text(), nullable=True),
    sa.Column('official_title', sa.Text(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('origin_chamber', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('latest_action_date', sa.Date(), nullable=True),
    sa.Column('latest_action', sa.Text(), nullable=True),
    sa.Column('enacted_as', sa.String(length=50), nullable=True),
    sa.Column('law_number', sa.String(length=50), nullable=True),
    sa.Column('session_law', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id'),
    sa.UniqueConstraint('congress_id', 'bill_type', 'number')
    )
    op.create_table('committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('house_committee_id', sa.String(length=20), nullable=True),
    sa.Column('senate_committee_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('chamber', sa.String(length=20), nullable=True),
    sa.Column('committee_type', sa.String(length=50), nullable=True),
    sa.Column('parent_committee_id', sa.Integer(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.ForeignKeyConstraint(['parent_committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('fec_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('contributor_name', sa.String(length=200), nullable=True),
    sa.Column('contributor_city', sa.String(length=100), nullable=True),
    sa.Column('contributor_state', sa.String(length=50), nullable=True),
    sa.Column('contributor_zip', sa.String(length=20), nullable=True),
    sa.Column('employer', sa.String(length=200), nullable=True),
    sa.Column('occupation', sa.String(length=200), nullable=True),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contribution_type', sa.String(length=50), nullable=True),
    sa.Column('memo_code', sa.String(length=1), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('election_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['fec_committees.fec_committee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fec_disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('payee_name', sa.String(length=200), nullable=True),
    sa.Column('payee_city', sa.String(length=100), nullable=True),
    sa.Column('payee_state', sa.String(length=50), nullable=True),
    sa.Column('payee_zip', sa.String(length=20), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=False),
    sa.Column('disbursement_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('disbursement_type', sa.String(length=50), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['fec_committees.fec_committee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fec_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_number', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('filing_status', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('xml_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['fec_committees.fec_committee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_number')
    )
    op.create_table('fec_independent_expenditures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('candidate_id', sa.String(length=20), nullable=True),
    sa.Column('support_oppose', sa.String(length=10), nullable=True),
    sa.Column('expenditure_date', sa.Date(), nullable=False),
    sa.Column('expenditure_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expenditure_type', sa.String(length=50), nullable=True),
    sa.Column('memo_code', sa.String(length=1), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=True),
    sa.Column('candidate_office', sa.String(length=20), nullable=True),
    sa.Column('candidate_state', sa.String(length=50), nullable=True),
    sa.Column('candidate_district', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['fec_candidates.fec_candidate_id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['fec_committees.fec_committee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fec_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.String(length=20), nullable=True),
    sa.Column('report_year', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('receipts', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('disbursements', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cash_on_hand', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debt_owed', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('individual_contributions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pac_contributions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('candidate_contributions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['fec_committees.fec_committee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filing_type', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobbying_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('senator_bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('rep_bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('house_member_id', sa.String(length=20), nullable=True),
    sa.Column('senate_member_id', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['lobbying_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobbying_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('issue_code', sa.String(length=10), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('specific_issues', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['lobbying_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lobbying_lobbyists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('lobbyist_name', sa.String(length=200), nullable=True),
    sa.Column('covered_official_position', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['lobbying_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('district', sa.Integer(), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=False),
    sa.Column('class', sa.Integer(), nullable=True),
    sa.Column('state_rank', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('how_ended', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opensecrets_legislators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('opensecrets_id', sa.String(length=20), nullable=True),
    sa.Column('firstlast', sa.String(length=200), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('office', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('first_elected', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.String(length=10), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('fax', sa.String(length=30), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('webform', sa.Text(), nullable=True),
    sa.Column('congress_office', sa.Text(), nullable=True),
    sa.Column('bioguide_id', sa.String(length=20), nullable=True),
    sa.Column('votesmart_id', sa.Integer(), nullable=True),
    sa.Column('fec_id', sa.String(length=20), nullable=True),
    sa.Column('govtrack_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opensecrets_id')
    )
    op.create_table('stock_disclosures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('treaty_number', sa.Integer(), nullable=True),
    sa.Column('resolution_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('amendments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('amendment_type', sa.String(length=20), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=True),
    sa.Column('proposed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('bill_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('action_time', sa.DateTime(), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('record_id', sa.String(length=50), nullable=True),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_committees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_cosponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('is_original_cosponsor', sa.Boolean(), nullable=True),
    sa.Column('sponsorship_date', sa.Date(), nullable=True),
    sa.Column('withdrawal_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_description', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('version_code', sa.String(length=20), nullable=True),
    sa.Column('version_description', sa.String(length=200), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=20), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('financial_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('party_name', sa.String(length=300), nullable=True),
    sa.Column('terms_or_date', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['financial_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=300), nullable=True),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('value_low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('value_high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_type', sa.String(length=50), nullable=True),
    sa.Column('income_low', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('income_high', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['financial_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_gifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['financial_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('organization_name', sa.String(length=300), nullable=True),
    sa.Column('position_title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['financial_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_travel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=300), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('dates', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['financial_disclosures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nominations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('position_title', sa.Text(), nullable=True),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('nominee_name', sa.String(length=200), nullable=True),
    sa.Column('nominee_state', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committees.id'], ),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id')
    )
    op.create_table('opensecrets_candidate_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislator_id', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('firstlast', sa.String(length=200), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=True),
    sa.Column('party', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('spent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cash_on_hand', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('debt', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['opensecrets_legislators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opensecrets_contributors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislator_id', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=300), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pacs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('indivs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['opensecrets_legislators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opensecrets_industry_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislator_id', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.String(length=10), nullable=True),
    sa.Column('industry_name', sa.String(length=200), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pacs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('indivs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['opensecrets_legislators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opensecrets_sector_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legislator_id', sa.Integer(), nullable=True),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=True),
    sa.Column('sector_id', sa.String(length=10), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('pacs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('indivs', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['opensecrets_legislators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('related_bill_id', sa.Integer(), nullable=True),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['related_bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disclosure_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('filer_name', sa.String(length=200), nullable=True),
    sa.Column('filer_relation', sa.String(length=50), nullable=True),
    sa.Column('asset_name', sa.String(length=300), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('transaction_amount_low', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_amount_high', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ownership_type', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disclosure_id'], ['stock_disclosures.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nomination_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomination_id', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('congress_gov_id', sa.String(length=50), nullable=True),
    sa.Column('congress_id', sa.Integer(), nullable=True),
    sa.Column('chamber', sa.String(length=20), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=True),
    sa.Column('roll_number', sa.Integer(), nullable=False),
    sa.Column('vote_date', sa.Date(), nullable=False),
    sa.Column('vote_time', sa.Time(), nullable=True),
    sa.Column('question', sa.String(length=200), nullable=True),
    sa.Column('vote_type', sa.String(length=50), nullable=True),
    sa.Column('vote_result', sa.String(length=50), nullable=True),
    sa.Column('vote_description', sa.Text(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('amendment_id', sa.Integer(), nullable=True),
    sa.Column('nomination_id', sa.Integer(), nullable=True),
    sa.Column('majority_position', sa.String(length=20), nullable=True),
    sa.Column('total_yes', sa.Integer(), nullable=True),
    sa.Column('total_no', sa.Integer(), nullable=True),
    sa.Column('total_present', sa.Integer(), nullable=True),
    sa.Column('total_not_voting', sa.Integer(), nullable=True),
    sa.Column('required_majority', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['amendment_id'], ['amendments.id'], ),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['congress_id'], ['congresses.id'], ),
    sa.ForeignKeyConstraint(['nomination_id'], ['nominations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('congress_gov_id'),
    sa.UniqueConstraint('congress_id', 'chamber', 'roll_number')
    )
    op.create_table('vote_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['vote_id'], ['votes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_positions')
    op.drop_table('votes')
    op.drop_table('nomination_actions')
    op.drop_table('stock_transactions')
    op.drop_table('related_bills')
    op.drop_table('opensecrets_sector_contributions')
    op.drop_table('opensecrets_industry_contributions')
    op.drop_table('opensecrets_contributors')
    op.drop_table('opensecrets_candidate_summaries')
    op.drop_table('nominations')
    op.drop_table('financial_travel')
    op.drop_table('financial_positions')
    op.drop_table('financial_gifts')
    op.drop_table('financial_assets')
    op.drop_table('financial_agreements')
    op.drop_table('committee_reports')
    op.drop_table('committee_memberships')
    op.drop_table('bill_texts')
    op.drop_table('bill_summaries')
    op.drop_table('bill_subjects')
    op.drop_table('bill_cosponsors')
    op.drop_table('bill_committees')
    op.drop_table('bill_actions')
    op.drop_table('amendments')
    op.drop_table('treaties')
    op.drop_table('stock_disclosures')
    op.drop_table('opensecrets_legislators')
    op.drop_table('member_terms')
    op.drop_table('lobbying_lobbyists')
    op.drop_table('lobbying_issues')
    op.drop_table('lobbying_contacts')
    op.drop_table('ingestion_logs')
    op.drop_table('financial_disclosures')
    op.drop_table('fec_totals')
    op.drop_table('fec_independent_expenditures')
    op.drop_table('fec_filings')
    op.drop_table('fec_disbursements')
    op.drop_table('fec_contributions')
    op.drop_table('committees')
    op.drop_table('bills')
    op.drop_table('api_rate_limits')
    op.drop_table('members')
    op.drop_table('lobbying_disclosures')
    op.drop_table('federal_register')
    op.drop_table('fec_committees')
    op.drop_table('fec_committee_candidates')
    op.drop_table('fec_candidates')
    op.drop_table('data_sources')
    op.drop_table('data_quality_checks')
    op.drop_table('congressional_records')
    op.drop_table('congresses')
    op.drop_table('chambers')
    op.drop_table('cfr_entries')
    # ### end Alembic commands ###
